server:
  port: 8189
  servlet:
    context-path: /task-manager
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=task_manager_dir
    username: postgres
    password: postgres
  timeleaf:
    encoding: UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false